### PR TITLE
Fix multiple issues

### LINKED ISSUE #26: Logs are been sent as a batch once in 10 minutes
I couldn't find the way to set the time interval definition.
In grafana I can see the logs arriving each 10 minutes. Their 'parsed timestamp' is almost identical because of that,
is there any way to set to the time interval value?

### PR DESCRIPTION
**Pull request by Falco20019**
Fixes #26 and another problem with having reg-ex like data parsed.

There also seems to be some bottleneck in the formatting. I will analyze that in a separate PR.

### CODE REVIEW

**Comment by JosephWoodward** [comment]
@Falco20019 Great, thanks for this. Is this good to merge?

**Comment by Falco20019** [comment]
I also made the `LokiBatchFormatter` public. This would have allowed working around #26 and might help in other use cases as well (like trying to ensure that all data is sent before closing).

**Comment by JosephWoodward** [comment]
@Falco20019 Sounds great, is this ready to review/merge?

**Comment by Falco20019** [comment]
Yep, ready to review

**Comment by Falco20019** [comment]
@JosephWoodward Friendly ping

**Comment by michaelosthege** [comment]
Trying to diagnose why logs don't show up in Loki, I ended up here.
Could it be that the most recent Loki version already removed the old http API ?

**Comment by Falco20019** [comment]
I can check the output with the latest version of Loki next Monday since I'm out of office. Possible that the old endpoint was disabled. I can check if it's easy to adjust to the new one.

**Comment by michaelosthege** [comment]
@Falco20019 did you already get a chance to check the new version?

**Comment by Falco20019** [comment]
> @Falco20019 did you already get a chance to check the new version?

Hi @michaelosthege, I just tried it with the latest images and everything seems to work as usual.

```
REPOSITORY             TAG           IMAGE ID       CREATED         SIZE
grafana/grafana        latest        825dc00311e2   24 hours ago    206MB
grafana/loki           latest        9915c32fc0ce   40 hours ago    61.6MB
```

Just make sure, that you have port 3100 forwarded and it should work.

**Comment by Falco20019** [comment]
@JosephWoodward Thanks for merging. For when is the next release planned? We are currently for some time on the beta now :) could you at least create a new beta so that it's easy to use from NuGet?

**Comment by michaelosthege** [comment]
I finally figured out why log messages were not arriving in Loki: The system time on my Raspberry Pi IoT Core without internet connectivity was off by over a year.

So whoever ends up reading this: Synchronize your clock.

**Comment by JosephWoodward** [comment]
@Falco20019 I've deployed a v4 beta, if you'd like to give it a try and let me know if you find any issues. @michaelosthege has kindly contributed a github workflow that will allow me to easily release changes in future so you shouldn't have to wait so long for future released, thanks for all of your work!

**Comment by Falco20019** [comment]
I'm back at work starting July 14th and will look into it then.

**Pull request merged**
