### PR TITLE
Added support for Serilog Settings Configuration

### LINKED ISSUE #6: Feature request: Support for using Serilog Settings Configuration
Idea is to support configuration of Loki sync over Serilog Settings Configuration https://github.com/serilog/serilog-settings-configuration.

If this is already available then only documentation is needed.

I guess that Sink constructor has to be change to use primitive types for configuration of Url, User and Pass

### PR DESCRIPTION
**Pull request by Aragas**
Fixes #6 
A simple Serilog Settings Configuration implementation that supports both NoAuthCredentials and BasicAuthCredentials.
Won't work with ILogLabelProvider, but it should't be a problem after merging #7, can be replaced with Enrichers, and it won't work with a custom LokiHttpClient.

### CODE REVIEW

**Comment by Aragas** [comment]
For future googlers, here's an example of the configuration file
```json
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.Loki" ],
    "Enrich": [ "FromLogContext" ],
    "WriteTo": [
      {
        "Name": "LokiHttp",
        "Args": {
          "serverUrl": "https://loki.com:3100",
		  "username": "user",
		  "password": "pwd"
        }
      }
    ]
  }
}
```

**Comment by EraYaN** [comment]
If this could be merged, that would be very useful.

**Comment by mishamyte** [comment]
@JosephWoodward could you, please, find some time to review this PR and merge it? It would be pretty nice. We are waiting for the release of this sink with that functionality

**Comment by JosephWoodward** [comment]
Sorry, I've only just remember this was here! Yes, I'll get around to this right away.

**Comment by JosephWoodward** [comment]
Sorry this has taken so long, I'll try and get it deployed tonight.

**Comment by mishamyte** [comment]
No problem)) We've got another Loki sink with all required functionality) But thanks for your work. Really appreciate it.

**Pull request merged**
