### PR TITLE
Added support for additional configuration overloads

### PR DESCRIPTION
**Pull request by AnderssonPeter**
Added support for additional configuration overloads also added documentation how to configure with appsettings.json

### CODE REVIEW

**Comment by EraYaN** [comment]
With the new behavior in 3.0.1-beta (with the actual 3.0.0 binaries) this is required to keep using the properties -> labels stuff. Cause otherwise I see no way to inject a `ILogLabelProvider` anywhere.

**Comment by AnderssonPeter** [comment]
I found the https://github.com/mishamyte/serilog-sinks-grafana-loki nuget and the 5.1.0-beta has merged the functionallty i need so you dont have to merge this for me. (I needed a library that could send the data in json format)

**Comment by EraYaN** [comment]
I would still love this functionality though.

**Comment by aviezzi** [comment]
Hi @JosephWoodward 
any news about merge?

**Comment by JosephWoodward** [comment]
Merged, I'll try get a new release out this weekend to test.

**Pull request merged**
