### PR TITLE
Unquote simple string values

### PR DESCRIPTION
**Pull request by Falco20019**
Fixes #35

### CODE REVIEW

**Comment by Falco20019** [comment]
@jincod Please check if this fixes your problem.

**Comment by Falco20019** [comment]
@JosephWoodward Feel free to fix this as `3.0.1` as only the `3.0.1-beta1` was yet released 👍

**Comment by jincod** [comment]
@Falco20019 LGTM!

Thank you for your help!

**Comment by JosephWoodward** [comment]
Thanks for this @Falco20019 and @jincod.

I'll get this released as part of `3.0.1` later today.

**Pull request merged**
