### PR TITLE
Added Default LogLabel provider with PropertiesAsLabels option

### PR DESCRIPTION
**Pull request by jincod**

### CODE REVIEW

**Comment by Falco20019** [comment]
We are also looking forward to this :)

**Comment by jincod** [comment]
Hi @Falco20019 

You can use this now

- Download `Serilog.Sinks.Loki.3.0.0-alpha.nupkg` to `<root_project>/libs/Serilog.Sinks.Loki.3.0.0-alpha.nupkg` from https://github.com/jincod/Serilog-Sinks-Loki/releases/tag/v3.0.0-alpha
- Add `Nuget.config` to `<root_project>/Nuget.config`

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
        <packageSources>
                <add key="local" value=".\libs" />
        </packageSources>
</configuration>
```

**Comment by Falco20019** [comment]
@jincod Thanks :) I had a look at #15 which is partly overlapping but more flexible. I need some properties as labels (like `SourceContext`) which would not be possible with this approach. So I started my build based on that branch.

**Comment by JosephWoodward** [comment]
@Falco20019 Interested to see what you come up with. I've been slowly working through #15 but as it's quite a large PR there's a lot changing in there and I need to get back up to speed.

**Comment by JosephWoodward** [comment]
I'm also thinking PropertiesAsLabels should be false by default to prevent an accidental explosion of labels which could prove an issue with high throughout systems. Instead you should have to explicitly opt in to the property being turned into a label so that such a change is visible in a PR instead of being unaware of it happening.

**Comment by Falco20019** [comment]
Not sure if I would merge #15 and #22. Since #15 is introducing a flag for the strategy, this behavior can already be defined there. I think it might be still useful to be able to do it from the provider too, but it would need to be rebased once #15 is in since they both target the same area and would lead to conflicts.

**Comment by jincod** [comment]
@JosephWoodward 

I've done some refactoring and introduced `PropertiesAsLabels` as list of required labels

**Pull request merged**
