### PR TITLE
Added contextual log labels.

### PR DESCRIPTION
**Pull request by m-mccormick**
Screenshot from 2020-02-13 19-06-42

### CODE REVIEW

**Comment by JosephWoodward** [comment]
Oh nice, thanks for this!

**Comment by m-mccormick** [comment]
No problem, it seems like useful functionality. If you do merge, could you please publish a new nuget package?

**Comment by m-mccormick** [comment]
Alternative to https://github.com/JosephWoodward/Serilog-Sinks-Loki/pull/7/commits/d22abe2945017c1edb1edff86e9fd4bf4ced161f since that would be a breaking change: grafana/grafana#22258

**Comment by JosephWoodward** [comment]
Great, thanks. I'll be looking to merge/release this in the next few days.

**Comment by JosephWoodward** [comment]
@m-mccormick, a new package has been released which includes your changes. Thanks for your contribution! https://www.nuget.org/packages/Serilog.Sinks.Loki/2.0.0

**Comment by m-mccormick** [comment]
@JosephWoodward  Thank you!

**Pull request merged**
